apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - svc-headless.yaml
  - svc.yaml
  - statefulset.yaml
  - init-replset-job.yaml
  - mongo-express-deployment.yaml
  - mongo-express-svc.yaml
