apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:1.0.0
          env:
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-root-credentials
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-root-credentials
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              value: "mongo-0.mongo"
            # better: use full connection string for replica set:
            - name: ME_CONFIG_MONGODB_URL
              value: "mongodb://root:CHANGE_ME_STRONG_PASSWORD@mongo-0.mongo:27017,mongo-1.mongo:27017/?replicaSet=rs0"
          ports:
            - containerPort: 8081
              name: http
