apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base

patchesStrategicMerge:
  - mailu-node.yaml
  - mautic-node.yaml
  - mysql-node.yaml

secretGenerator:
  - name: email-credentials
    files:
      - secrets.env
