apiVersion: v1
kind: Service
metadata:
  name: mailu
spec:
  selector:
    app: mailu
  ports:
    - protocol: TCP
      port: 25
      targetPort: 25
    - protocol: TCP
      port: 587
      targetPort: 587
    - protocol: TCP
      port: 143
      targetPort: 143
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
