resources:
  - bootstrap/storageclass-local.yaml
  - namespace.yaml
  - rbac/sa-secret-generator.yaml
  - rbac/role-secret-generator.yaml
  - rbac/rolebinding-secret-generator.yaml
  - bootstrap/secret-generator-job.yaml
  - mysql/pvc.yaml
  - mysql/deployment.yaml
  - mysql/service.yaml
  - app/pvc.yaml
  - app/deployment.yaml
  - app/service.yaml
