apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storageclass-local.yaml
  - namespace.yaml
  - mysql/
  - app/

secretGenerator:
  - name: mysql-secret
    namespace: emailsys
    literals:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
    options:
      disableNameSuffixHash: true
