apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - crds.yaml
  - common.yaml
  - operator.yaml
  - cluster.yaml
  - storage-nvme.yaml
  - storage-ssd.yaml
