apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Namespace שבו יפעל Rook
  - namespace.yaml

  # הרשאות RBAC
  - rolebinding.yaml
  - scc.yaml

  # Application שמפעיל את Helm chart של Rook Ceph
  - rook-ceph-app.yaml
