apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common.yaml      # Namespace, ServiceAccounts וכו’
  - operator.yaml    # Rook Operator
  - cluster.yaml     # CephCluster + Pools + Dashboard
