apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailu
  template:
    metadata:
      labels:
        app: mailu
    spec:
      containers:
        - name: mailu
          image: mailu/mailu:1.9
          ports:
            - containerPort: 25
            - containerPort: 587
            - containerPort: 143
            - containerPort: 80
          volumeMounts:
            - mountPath: /data
              name: mailu-data
      volumes:
        - name: mailu-data
          persistentVolumeClaim:
            claimName: mailu-pvc
